### ISSUE TITLE
Matching error: TypeError: Choices must be a sequence of strings

### ISSUE THREAD

**Issue by TrigonaMinima** [rapidfuzz/RapidFuzz#19]
Here is the reproducible example:

```python
from rapidfuzz import process
ch = {'abc\x00', 'abcd:\x00', 'abc:\x00d'}
process.extractOne("abc", ch)
```

And here's the traceback

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Anaconda/envs/hing/lib/python3.7/site-packages/rapidfuzz/process.py", line 70, in extractOne
    return rapidfuzz._process.extractOne(query, choices, score_cutoff, bool(processor))
TypeError: Choices must be a sequence of strings
```

As a workaround, I can remove the offending character (`\x00`) from each of the choices, but I have a lot many of these lists. And the costs will add up.

**Comment by maxbachmann** [comment]
Thanks for reporting. I did just push Version 0.5.3 which should fix this problem

```console
> from rapidfuzz import process
> ch = {'abc\x00', 'abcd:\x00', 'abc:\x00d'}
> process.extractOne("abc", ch)
('abc\x00', 100.0)
```
